# Generated by Django 4.2 on 2023-04-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_csv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='image',
            new_name='file',
        ),
    ]
