# Generated by Django 4.2 on 2023-04-16 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_csv_eps_csv_min_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='eps',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальное расстояние между точками'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='file',
            field=models.FileField(upload_to='csv_files/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='min_samples',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальное число соседей в кластере'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Файл картинки'),
        ),
    ]
